// Copies captured screenshots into public/ and cuts the gameplay segments the videos use.
import { cpSync, mkdirSync, existsSync, readdirSync } from 'node:fs'
import { execFileSync } from 'node:child_process'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const OUT = join(here, '..', '.out')
const FFMPEG = join(OUT, 'app', 'resources', 'bin', 'ffmpeg.exe')
const pub = join(here, 'public')

for (const layout of ['wide', 'compact']) {
  mkdirSync(join(pub, 'shots', layout), { recursive: true })
  cpSync(join(OUT, 'shots', layout), join(pub, 'shots', layout), {
    recursive: true,
    filter: src => !/probe|library-grid/.test(src),
  })
}

const clip = id => {
  for (const dir of ['clips', 'staging']) {
    const p = join(OUT, dir, `${id}.mp4`)
    if (existsSync(p)) return p
  }
  throw new Error('missing clip ' + id)
}

// [output, clip id, start seconds, duration]
const SEGMENTS = [
  ['game-won', '2026-09-28_23-30-00_VALORANT', 38, 12],
  ['game-open', '2026-09-28_23-30-00_VALORANT', 0, 6],
  ['tekken-fire', '2026-09-28_02-41-39_TEKKEN_8', 17, 8],
  ['league-fight', '2026-09-27_21-41-34_League_of_Legends', 0, 6],
]
mkdirSync(join(pub, 'media'), { recursive: true })
for (const [name, id, start, dur] of SEGMENTS) {
  const out = join(pub, 'media', `${name}.mp4`)
  if (existsSync(out) && !process.argv.includes('--force')) continue
  execFileSync(FFMPEG, [
    '-v', 'error', '-y', '-ss', String(start), '-i', clip(id), '-t', String(dur),
    '-an', '-r', '30', '-c:v', 'libx264', '-crf', '17', '-preset', 'medium', '-pix_fmt', 'yuv420p',
    '-movflags', '+faststart', out,
  ])
  console.log('segment', name)
}
// Real library thumbnails (generated by the app) and full-size gameplay frames for the motion videos.
mkdirSync(join(pub, 'thumbs'), { recursive: true })
cpSync(join(OUT, 'profile', 'userdata', 'thumbnails'), join(pub, 'thumbs'), { recursive: true, filter: src => !src.endsWith('audio') })
mkdirSync(join(pub, 'frames'), { recursive: true })
for (const f of readdirSync(join(here, '..', 'sites', 'assets', 'frames'))) {
  if (f.endsWith('-1920.webp')) cpSync(join(here, '..', 'sites', 'assets', 'frames', f), join(pub, 'frames', f.replace('-1920', '')))
}
console.log('assets synced')
